# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' fastlm
#' @param X mat
#' @param y vector
#' @param wi vector
#' @export
fastlm <- function(X, y, wi) {
    .Call(`_blblm_fastlm`, X, y, wi)
}

